version: '3.8'
services:

  postgres-db:
    image: postgres:14
    container_name: postgresYaEShop
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: hack_template
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=500"]
    networks:
      - yaeshop-network

  minio:
    image: minio/minio:latest
    container_name: minioYaEShop
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: sUperSecretKeyFooBar
    command: server /data --console-address ":9090"

volumes:
  postgres_data:


networks:
  yaeshop-network:
