spring:
  datasource:
    url: ${DATA_SOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

minio:
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  url: http://${MINIO_HOST}
  public-url: ${MINIO_PUBLIC_URL}
